### ISSUE TITLE
a simpler explanation or example is needed for subword step

### ISSUE THREAD

**Issue by ican24** [ymoslem/MT-Preparation#1]
Dear Yasmin,

I am trying to use MT-Preparation for my development in OpenNMT-tf.
Unfortunatelly my attempts were failed: onmt-main with infer method is unable to translate this way.
I may suppose that I did mistake(s) to launch MT-Preparation scripts in the subword and further stages?
I would appreciate if you could add some explaination with simple examples.
For example, what you mean exactly <source_pred_file> and <target_pred_file>? 
`
python3 subword.py <source_model_file> <target_model_file> <source_pred_file> <target_pred_file>
`

Thank you in advance!

**Comment by ymoslem** [comment]
Hi Artak!

If you did not use SentencePiece subwording for preparing your data *before* training, do *not* use it before translation. In this case, your inference issue might not be related to these scripts.

---

> what you mean exactly <source_pred_file> and <target_pred_file>?
> python3 subword.py <source_model_file> <target_model_file> <source_pred_file> <target_pred_file>

In this case, you have three steps:
1. train SentencePiece subwording models using the first script [1-train_bpe.py](https://github.com/ymoslem/MT-Preparation/blob/main/subwording/1-train_bpe.py) or [1-train_unigram.py](https://github.com/ymoslem/MT-Preparation/blob/main/subwording/1-train_unigram.py), which creates two *.model files and two *.vocab files, for the input source and target dataset files.
2. apply the generated SentencePiece models on the source and target dataset files using the second script [2-subword.py](https://github.com/ymoslem/MT-Preparation/blob/main/subwording/2-subword.py). The first two arguments are for the models and the last two arguments are for the source and target dataset files.
3. after translation, desubword the generated prediction files using the script [3-desubword.py](https://github.com/ymoslem/MT-Preparation/blob/main/subwording/3-desubword.py).

As I said, if you did not apply subwording before training, you do not need it for translation.

I hope this makes it clearer now.

**Comment by ican24** [comment]
Dear Yasmin,

Thank you for your explanation!
I'll try again more carefully.
